version: 2.1

executors:
  docker-executors:
    docker:
      - image: docker:latest
    working_directory: ~/repo

jobs:
  build_and_push:
    executor: docker-executors
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Tag Docker image
          command: |
            TAG=$(git rev-parse --short HEAD)
            echo "TAG=${TAG}" # Debugging: Output the tag
            docker build -t $DOCKER_USERNAME/portfolio-fe:$TAG ./portfolio-frontend
      
      - run:
          name: Docker Hub Login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Push Docker image
          command: |
            TAG=$(git rev-parse --short HEAD)
            docker push $DOCKER_USERNAME/portfolio-fe:$TAG
      
  deploy:
    executor: docker-executors
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Pull Docker image
          command: |
            ssh -o StrictHostKeyChecking=no -i $CIVO_KEY root@$CIVO_IP "docker pull $DOCKER_USERNAME/porfolio-fe:$IMAGE_TAG"
      
      - run:
          name: Stop Old Docker Container
          command: |
            ssh -o StrictHostKeyChecking=no -i $CIVO_KEY civo@$CIVO_IP "docker stop portfolio-container || true"
            ssh -o StrictHostKeyChecking=no -i $CIVO_KEY civo@$CIVO_IP "docker rm portfolio-container || true"
      
      - run:
          name: Deploy Docker Container
          command: |
            ssh -o StrictHostKeyChecking=no -i $CIVO_KEY civo@$CIVO_IP "docker run -d --name portfolio-container -p 80:3000 $DOCKER_USERNAME/porfolio-fe:$IMAGE_TAG"
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_push
    - deploy:
        requires:
          - build_and_push