version: 2.1

executors:
  docker-executors:
    docker:
      - image: docker:latest
    working_directory: ~/repo

jobs:
  build_and_push:
    executor: docker-executors
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Tag Docker image
          command: |
            TAG=$(git rev-parse --short HEAD)
            echo "TAG=${TAG}" # Debugging: Output the tag
            docker build -t $DOCKER_USERNAME/portfolio-fe:$TAG ./portfolio-frontend
      
      - run:
          name: Docker Hub Login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Push Docker image
          command: |
            TAG=$(git rev-parse --short HEAD)
            docker push $DOCKER_USERNAME/portfolio-fe:$TAG
      
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
          name: Install git
          command: apt-get update && apt-get install -y git

      - run:
          name: Pull Docker Image
          command: |
            TAG=$(git rev-parse --short HEAD)
            ssh -oStrictHostKeyChecking=no -v $CIVO_USER@$CIVO_IP "docker pull $DOCKER_USERNAME/portfolio-fe:$TAG"

      - run:
          name: Delete Old Docker Image
          command: |
            ssh -oStrictHostKeyChecking=no -v $CIVO_USER@$CIVO_IP "docker image prune -f"

      - run:
          name: Deploy New Docker Image
          command: |
            TAG=$(git rev-parse --short HEAD)
            ssh -oStrictHostKeyChecking=no -v $CIVO_USER@$CIVO_IP "docker run -d --name portfolio-app -p 80:3000 $DOCKER_USERNAME/portfolio-fe:$TAG"

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_push
    - deploy:
        requires:
          - build_and_push