version: 2.1

executors:
  docker-executors:
    docker:
      - image: docker:latest
    working_directory: ~/repo

jobs:
  build_and_push:
    executor: docker-executors
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/porfolio-fe:latest ./portfolio-frontend

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_push