version: 2.1

executors:
  docker-executors:
    docker:
      - image: docker:latest
    working_directory: ~/repo

jobs:
  build_and_push:
    executor: docker-executors
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Tag Docker image
          command: |
            docker build -t $DOCKER_USERNAME/portfolio-fe:latest ./portfolio-frontend
      
      - run:
          name: Docker Hub Login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Push Docker image
          command: |
            TAG=$(git rev-parse --short HEAD)
            docker push $DOCKER_USERNAME/portfolio-fe:latest
      
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v $CIVO_USER@$CIVO_IP "./portfolio_redeploy.sh"

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_push
    - deploy:
        requires:
          - build_and_push