version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:20.10.24
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: docker build -f portfolio-frontend/Dockerfile -t test-app portfolio-frontend

workflows:
  version: 2
  build:
    jobs:
      - build
