version: 2.1

executors:
  docker-executors:
    docker:
      - image: docker:latest
    working_directory: ~/repo

jobs:
  build_and_push:
    executor: docker-executors
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Docker Image tag
          command: |
            TAG=$(git rev-parse --short HEAD)
            echo "TAG=${TAG}"
            export IMAGE_TAG=$TAG

      - run:
          name: Tag Docker image
          command: |
            docker build -t $DOCKER_USERNAME/portfolio-fe:$IMAGE_TAG ./portfolio-frontend
      
      - run:
          name: Validate IMAGE_TAG
          command: |
            echo "Validating IMAGE_TAG..."
            if [ -z "$IMAGE_TAG" ]; then
              echo "IMAGE_TAG is empty!"
              exit 1
            fi
            if ! echo "$IMAGE_TAG" | grep -Eq '^[a-zA-Z0-9_.-]+$'; then
              echo "IMAGE_TAG contains invalid characters!"
              exit 1
            fi
            echo "IMAGE_TAG is valid: $IMAGE_TAG"
      
      - run:
          name: Docker Hub Login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Push Docker image
          command: |
            docker push $DOCKER_USERNAME/portfolio-fe:$IMAGE_TAG
      
  deploy:
    executor: docker-executors
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Pull Docker image
          command: |
            ssh -o StrictHostKeyChecking=no -i $CIVO_KEY civo@$CIVO_IP "docker pull $DOCKER_USERNAME/porfolio-fe:$IMAGE_TAG"
      
      - run:
          name: Stop Old Docker Container
          command: |
            ssh -o StrictHostKeyChecking=no -i $CIVO_KEY civo@$CIVO_IP "docker stop portfolio-container || true"
            ssh -o StrictHostKeyChecking=no -i $CIVO_KEY civo@$CIVO_IP "docker rm portfolio-container || true"
      
      - run:
          name: Deploy Docker Container
          command: |
            ssh -o StrictHostKeyChecking=no -i $CIVO_KEY civo@$CIVO_IP "docker run -d --name portfolio-container -p 80:3000 $DOCKER_USERNAME/porfolio-fe:$IMAGE_TAG"
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_push
    - deploy:
        requires:
          - build_and_push