version: 2.1

executors:
  docker-executors:
    docker:
      - image: docker:latest
    working_directory: ~/repo

jobs:
  build_and_push:
    executor: docker-executors
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Tag Docker image
          command: |
            TAG=$(git rev-parse --short HEAD)
            echo "TAG=${TAG}" # Debugging: Output the tag
            docker build -t $DOCKER_USERNAME/portfolio-fe:$TAG ./portfolio-frontend
      
      - run:
          name: Docker Hub Login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Push Docker image
          command: |
            TAG=$(git rev-parse --short HEAD)
            docker push $DOCKER_USERNAME/portfolio-fe:$TAG
      
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install Civo CLI
          command: |
            wget https://github.com/civo/cli/releases/download/v1.0.40/civo-1.0.40-linux-amd64.tar.gz
            tar -xvf civo-1.0.40-linux-amd64.tar.gz
            sudo chmod +x civo
            sudo mv ./civo /usr/local/bin/
            export CIVO_API_KEY_NAME=${CIVO_API_KEY_NAME:-circleci}
            civo apikey save --load-from-env

      - run:
            name: SSH into Instance and Manage Docker Images
            command: |
              # Pull the new Docker image on the instance
              ssh -o StrictHostKeyChecking=no -i $CIVO_SSH_KEY root@$CIVO_IP "docker pull $DOCKER_USERNAME/portfolio-fe:$IMAGE_TAG"
              
              # Remove old Docker container if exists
              ssh -o StrictHostKeyChecking=no -i $CIVO_SSH_KEY root@$CIVO_IP "docker rm -f my-app || true"
              
              # Remove old Docker image
              ssh -o StrictHostKeyChecking=no -i $CIVO_SSH_KEY root@$CIVO_IP "docker image prune -f"
              
              # Run new Docker container
              ssh -o StrictHostKeyChecking=no -i $CIVO_SSH_KEY root@$CIVO_IP "docker run -d --name my-app $DOCKER_USERNAME/portfolio-fe:$IMAGE_TAG"

      - run:
          name: Pull Docker Image
          command: |
            TAG=$(git rev-parse --short HEAD)
            civo instance ssh $CIVO_INSTANCE_ID --command "docker pull $DOCKER_USERNAME/portfolio-fe:$TAG"

      # Delete the old Docker image
      - run:
          name: Delete Old Docker Image
          command: |
          
            civo instance ssh $CIVO_INSTANCE_ID --command "docker image prune -f"

      # Deploy the new Docker image
      - run:
          name: Deploy New Docker Image
          command: |
            TAG=$(git rev-parse --short HEAD)
            civo instance ssh $CIVO_INSTANCE_ID --command "docker run -d --name portfolio-app -p 80:3000 $DOCKER_USERNAME/portfolio-fe:$TAG"

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_push
    - deploy:
        requires:
          - build_and_push