version: 2.1

executors:
  docker-executors:
    docker:
      - image: cimg/base:stable

jobs:
  build_and_push:
    executor: docker-executors
    steps:
      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/porfolio-fe:latest ./portfolio-frontend

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_push