apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio-ingress
  namespace: default # Change this to the correct namespace
spec:
  entryPoints:
    - web
    - websecure # Include this if you want HTTPS
  routes:
    - match: Host(`kube.pksinha.co.uk`)
      kind: Rule
      services:
        - name: portfolio-service
          port: 80
  tls:
    secretName: your-tls-secret # Replace with your actual TLS secret name
